// Client bundle for the space.
//
// Bundling is owned by the SDK so every space produces an identical
// production-mode React bundle. See @hatch/space-sdk/build for the
// canonical Bun.build() configuration (entrypoint, outdir, NODE_ENV
// define, asset naming, tailwind plugin).

import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { buildClient } from "@hatch/space-sdk/build";

const artifactRoot = join(import.meta.dir, "..");
const generatedPath = join(import.meta.dir, "src", "generated-build.ts");
const hash = createHash("sha256");

async function hashTree(root) {
  const entries = await readdir(root, { withFileTypes: true });
  entries.sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of entries) {
    const path = join(root, entry.name);
    if (path === generatedPath) continue;
    if (entry.isDirectory()) await hashTree(path);
    else if (entry.isFile()) {
      hash.update(relative(artifactRoot, path));
      hash.update(await readFile(path));
    }
  }
}

for (const path of [join(artifactRoot, "client", "src"), join(artifactRoot, "server", "src"), join(artifactRoot, "drizzle")]) {
  await hashTree(path);
}
for (const path of ["space.json", "package.json", "bun.lock", "client/tsconfig.json", "server/tsconfig.json", "client/build.mjs"]) {
  hash.update(path);
  hash.update(await readFile(join(artifactRoot, path)));
}
const buildHash = hash.digest("hex");
const buildTimestamp = new Date().toISOString();
const buildId = `${buildHash.slice(0, 12)}-${buildTimestamp.replace(/[-:.]/g, "")}`;
await writeFile(
  generatedPath,
  `// Generated by client/build.mjs. Do not edit by hand.\nexport const BUILD_HASH = ${JSON.stringify(buildHash)};\nexport const BUILD_TIMESTAMP = ${JSON.stringify(buildTimestamp)};\nexport const BUILD_ID = ${JSON.stringify(buildId)};\n`,
);

await buildClient();
