// Generated by client/build.mjs. Do not edit by hand.
export const BUILD_HASH = "df6612a12706eb66a6868784d5572ee89709288d72b84877c1dbb032dc6bfef7";
export const BUILD_TIMESTAMP = "2026-10-10T15:28:50.197Z";
export const BUILD_ID = "df6612a12706-20261010T152850197Z";
