// Generated by client/build.mjs. Do not edit by hand.
export const BUILD_HASH = "71d5296a18e5c4e45f80fde8740dc4681e1130d21acdfa762e698ce8e419f380";
export const BUILD_TIMESTAMP = "2026-10-10T00:40:57.815Z";
export const BUILD_ID = "71d5296a18e5-20261010T004057815Z";
