import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export type PerfSubsystemValues = { render?: number; terrain: number; streaming: number; entities: number; camera: number; hud: number; collision: number; enemyAi: number; audio: number; save: number };
export type PerfChunkLoadEvent = { timestamp: number; key: string; durationMs?: number; drawCalls?: number };
export type PerfSample = { timestamp: number; fps: number; frameMs: number; jankMs?: number; subsystems: PerfSubsystemValues; vehicleSpeed: number; activeEnemies: number; visibleEnemies: number; totalEnemies?: number; totalPickups?: number; activeProjectiles?: number; activeSparks?: number; activeDamageNumbers?: number; activeAudioVoices?: number; groundChunksCached?: number; groundCacheMiB?: number; groundQueueSlots?: number; renderScale?: number; renderMs?: number; drawCalls?: number; chunkBuildMs?: number; chunkBuildSteps?: number; chunkBuildCompletions?: number; chunkQueueDepth?: number; chunkQueuePeak?: number; chunksQueuedThisFrame?: number; visibleChunks?: number; chunkCanvasAllocations?: number; chunkCanvasReuses?: number; chunkPoolSize?: number; chunkLoadEvents: PerfChunkLoadEvent[] };

export const perfRecordings = sqliteTable("perf_recordings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  startedAt: integer("started_at", { mode: "timestamp_ms" }).notNull(),
  stoppedAt: integer("stopped_at", { mode: "timestamp_ms" }).notNull(),
  sampleCount: integer("sample_count").notNull(),
  averageFps: real("average_fps").notNull(),
  averageFrameMs: real("average_frame_ms").notNull(),
  hotspot: text("hotspot").notNull(),
  chunkLoadCount: integer("chunk_load_count").notNull(),
  samples: text("samples", { mode: "json" }).$type<PerfSample[]>().notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
}, (table) => [index("perf_recordings_started_idx").on(table.startedAt)]);

export const gameSave = sqliteTable("game_save", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ownerKey: text("owner_key").notNull().default("owner"),
  room: integer("room").notNull().default(1),
  level: integer("level").notNull().default(1),
  timeOfDay: real("time_of_day").notNull().default(0.38),
  hp: integer("hp").notNull().default(100),
  maxHp: integer("max_hp").notNull().default(100),
  coins: integer("coins").notNull().default(0),
  weaponName: text("weapon_name").notNull().default("Rustblade"),
  weaponDamage: real("weapon_damage").notNull().default(12),
  attackSpeed: real("attack_speed").notNull().default(1),
  rarity: text("rarity", { enum: ["Common", "Uncommon", "Rare", "Epic", "Legendary", "Relic"] }).notNull().default("Common"),
  meleeWeaponName: text("melee_weapon_name").notNull().default("Rustblade"),
  armorName: text("armor_name").notNull().default("Traveler Cloak"),
  armorDefense: integer("armor_defense").notNull().default(0),
  charmName: text("charm_name").notNull().default("None"),
  trinketName: text("trinket_name").notNull().default("None"),
  gadgetName: text("gadget_name").notNull().default("None"),
  flashlightOn: integer("flashlight_on", { mode: "boolean" }).notNull().default(false),
  uvEmitterOwned: integer("uv_emitter_owned", { mode: "boolean" }).notNull().default(false),
  uvEmitterOn: integer("uv_emitter_on", { mode: "boolean" }).notNull().default(false),
  soundMuted: integer("sound_muted", { mode: "boolean" }).notNull().default(false),
  controlScheme: text("control_scheme", { enum: ["joystick", "wasd"] }),
  critChance: real("crit_chance").notNull().default(0.05),
  keys: integer("keys").notNull().default(0),
  ironKeys: integer("iron_keys").notNull().default(0),
  goldKeys: integer("gold_keys").notNull().default(0),
  ancientKeys: integer("ancient_keys").notNull().default(0),
  vehicleKeyOwned: integer("vehicle_key_owned", { mode: "boolean" }).notNull().default(false),
  lifesteal: real("lifesteal").notNull().default(0),
  thorns: real("thorns").notNull().default(0),
  dashReduction: real("dash_reduction").notNull().default(0),
  moveSpeed: real("move_speed").notNull().default(0),
  pickupRadius: real("pickup_radius").notNull().default(0),
  items: text("items", { mode: "json" }).$type<string[]>().notNull().default([]),
  storedItems: text("stored_items", { mode: "json" }).$type<string[]>().notNull().default([]),
  baseStates: text("base_states", { mode: "json" }).$type<Array<{ id: "ember" | "frost" | "mire"; claimed: boolean; upgrades: Array<"spikes" | "lantern" | "cookfire"> }>>().notNull().default([]),
  dungeonProgress: text("dungeon_progress", { mode: "json" }).$type<Array<{ id: "meadow" | "ember" | "frost" | "sewer"; roomsCleared: number; foesDefeated: number; eliteDefeated: boolean }>>().notNull().default([]),
  dungeonBossesDefeated: text("dungeon_bosses_defeated", { mode: "json" }).$type<Array<"meadow" | "ember" | "frost" | "sewer">>().notNull().default([]),
  dungeonLootedChestIds: text("dungeon_looted_chest_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  sewerVisited: integer("sewer_visited", { mode: "boolean" }).notNull().default(false),
  sewerBossDefeated: integer("sewer_boss_defeated", { mode: "boolean" }).notNull().default(false),
  sewerLootedCacheIds: text("sewer_looted_cache_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  respawnBase: text("respawn_base", { enum: ["village", "ember", "frost", "mire"] }).notNull().default("village"),
  rawMeat: integer("raw_meat").notNull().default(0),
  cookedMeals: integer("cooked_meals").notNull().default(0),
  infectionLevel: real("infection_level").notNull().default(0),
  antibiotics: integer("antibiotics").notNull().default(0),
  herbs: integer("herbs").notNull().default(0),
  antiseptic: integer("antiseptic").notNull().default(0),
  gunAmmoState: text("gun_ammo_state", { mode: "json" }).$type<Array<{ name: string; magazine: number; reserve: number }>>().notNull().default([]),
  boltCount: integer("bolt_count").notNull().default(0),
  woodScraps: integer("wood_scraps").notNull().default(0),
  planks: integer("planks").notNull().default(0),
  barricades: text("barricades", { mode: "json" }).$type<Array<{ siteId: string; points: Array<{ id: string; hp: number; maxHp: number }> }>>().notNull().default([]),
  questState: text("quest_state", { enum: ["not_started", "active", "complete"] }).notNull().default("not_started"),
  questTravelOut: integer("quest_travel_out", { mode: "boolean" }).notNull().default(false),
  questTravelBack: integer("quest_travel_back", { mode: "boolean" }).notNull().default(false),
  frontierQuestState: text("frontier_quest_state", { enum: ["not_started", "active", "complete"] }).notNull().default("not_started"),
  npcMetIds: text("npc_met_ids", { mode: "json" }).$type<string[]>().notNull().default([]),
  npcQuestStates: text("npc_quest_states", { mode: "json" }).$type<Array<{ id: string; state: "not_started" | "active" | "complete" }>>().notNull().default([]),
  mainStoryState: text("main_story_state", { enum: ["not_started", "active", "complete"] }).notNull().default("not_started"),
  mainStoryChapter: integer("main_story_chapter").notNull().default(0),
  storyIntroSeen: integer("story_intro_seen", { mode: "boolean" }).notNull().default(false),
  veilTruthStage: integer("veil_truth_stage").notNull().default(0),
  veilTruthChoice: text("veil_truth_choice", { enum: ["mercy", "judgment", "doubt"] }),
  storyFlags: text("story_flags", { mode: "json" }).$type<string[]>().notNull().default([]),
  ruinedLootedSiteIds: text("ruined_looted_site_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  visitedBuildingIds: text("visited_building_ids", { mode: "json" }).$type<string[]>().notNull().default([]),
  activeInteriorId: text("active_interior_id"),
  interiorLootedContainerIds: text("interior_looted_container_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  interiorDefeatedEnemyIds: text("interior_defeated_enemy_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  mallVisited: integer("mall_visited", { mode: "boolean" }).notNull().default(false),
  mallBossDefeated: integer("mall_boss_defeated", { mode: "boolean" }).notNull().default(false),
  mallLootedContainerIds: text("mall_looted_container_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  rareLootDrops: text("rare_loot_drops", { mode: "json" }).$type<Array<{ id: number; itemId: string; x: number; y: number }>>().notNull().default([]),
  kills: integer("kills").notNull().default(0),
  headshots: integer("headshots").notNull().default(0),
  headshotKills: integer("headshot_kills").notNull().default(0),
  roomsCleared: integer("rooms_cleared").notNull().default(0),
  bossesDefeated: integer("bosses_defeated").notNull().default(0),
  hardcoreMode: integer("hardcore_mode", { mode: "boolean" }).notNull().default(false),
  nextRunHardcore: integer("next_run_hardcore", { mode: "boolean" }).notNull().default(false),
  hardcoreBossRewards: integer("hardcore_boss_rewards").notNull().default(0),
  runsStarted: integer("runs_started").notNull().default(1),
  openedChestIds: text("opened_chest_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  claimedPickupIds: text("claimed_pickup_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  claimedBreakableIds: text("claimed_breakable_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  defeatedEnemyIds: text("defeated_enemy_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  enemyRespawns: text("enemy_respawns", { mode: "json" }).$type<Array<{ id: number; respawnAt: number }>>().notNull().default([]),
  clearedRoomIds: text("cleared_room_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  secretOpenedRoomIds: text("secret_opened_room_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  exploredCells: text("explored_cells", { mode: "json" }).$type<string[]>().notNull().default([]),
  truckX: real("truck_x").notNull().default(1580),
  truckY: real("truck_y").notNull().default(15745),
  truckFuel: real("truck_fuel").notNull().default(82),
  truckHp: real("truck_hp").notNull().default(180),
  vehicles: text("vehicles", { mode: "json" }).$type<Array<{ id: string; x: number; y: number; hp: number; fuel: number; owned: boolean; inventory: string[] }>>().notNull().default([]),
  dogAdopted: integer("dog_adopted", { mode: "boolean" }).notNull().default(false),
  dogLevel: integer("dog_level").notNull().default(1),
  dogX: real("dog_x").notNull().default(1210),
  dogY: real("dog_y").notNull().default(15715),
  dogHp: real("dog_hp").notNull().default(64),
  dogKills: integer("dog_kills").notNull().default(0),
  zombieDogKills: integer("zombie_dog_kills").notNull().default(0),
  zombieCrowKills: integer("zombie_crow_kills").notNull().default(0),
  packHuntBonuses: integer("pack_hunt_bonuses").notNull().default(0),
  dogTagRelics: integer("dog_tag_relics").notNull().default(0),
  leatherScraps: integer("leather_scraps").notNull().default(0),
  specialEncountered: text("special_encountered", { mode: "json" }).$type<("tank"|"witch"|"boomer"|"smoker"|"hunter")[]>().notNull().default([]),
  specialKills: integer("special_kills").notNull().default(0),
  bileJars: integer("bile_jars").notNull().default(0),
  pipeBombs: integer("pipe_bombs").notNull().default(0),
  molotovs: integer("molotovs").notNull().default(0),
  rags: integer("rags").notNull().default(0),
  selectedThrowable: text("selected_throwable", { enum: ["pipeBomb", "molotov", "bileJar"] }).notNull().default("pipeBomb"),
  specialTrophies: text("special_trophies", { mode: "json" }).$type<string[]>().notNull().default([]),
  chestsOpened: integer("chests_opened").notNull().default(0),
  bloodMoons: integer("blood_moons").notNull().default(0),
  bloodMoonsSurvived: integer("blood_moons_survived").notNull().default(0),
  holdoutBestWaves: text("holdout_best_waves", { mode: "json" }).$type<Array<{ id: "ember" | "frost" | "mire"; wave: number }>>().notNull().default([]),
  holdoutCompletions: text("holdout_completions", { mode: "json" }).$type<Array<{ id: "ember" | "frost" | "mire"; count: number }>>().notNull().default([]),
  volatileKills: integer("volatile_kills").notNull().default(0),
  volatileEyes: integer("volatile_eyes").notNull().default(0),
  volatileTrophyOwned: integer("volatile_trophy_owned", { mode: "boolean" }).notNull().default(false),
  volatileNestDespawnedIds: text("volatile_nest_despawned_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  comboCrafts: integer("combo_crafts").notNull().default(0),
  weaponUpgrades: text("weapon_upgrades", { mode: "json" }).$type<Array<{ name: string; tier: number }>>().notNull().default([]),
  boxLocation: integer("box_location").notNull().default(0),
  boxPullsRemaining: integer("box_pulls_remaining").notNull().default(0),
  boxPoolState: text("box_pool_state", { mode: "json" }).$type<string[]>().notNull().default([]),
  yarrowLocation: integer("yarrow_location").notNull().default(0),
  perkInventory: text("perk_inventory", { mode: "json" }).$type<Array<{ id: "ironhide" | "swiftstride" | "quickfingers" | "secondWind" | "scavengerLuck"; count: number }>>().notNull().default([]),
  activePerks: text("active_perks", { mode: "json" }).$type<Array<{ id: "ironhide" | "swiftstride" | "quickfingers" | "secondWind" | "scavengerLuck"; expiresAt: number }>>().notNull().default([]),
  collectedRuleIds: text("collected_rule_ids", { mode: "json" }).$type<string[]>().notNull().default([]),
  readRuleIds: text("read_rule_ids", { mode: "json" }).$type<string[]>().notNull().default([]),
  runStartedAt: text("run_started_at").notNull().default(""),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
}, (table) => [uniqueIndex("game_save_owner_key_unique").on(table.ownerKey)]);
