import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const gameSave = sqliteTable("game_save", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ownerKey: text("owner_key").notNull().default("owner"),
  room: integer("room").notNull().default(1),
  level: integer("level").notNull().default(1),
  hp: integer("hp").notNull().default(100),
  maxHp: integer("max_hp").notNull().default(100),
  coins: integer("coins").notNull().default(0),
  weaponName: text("weapon_name").notNull().default("Rustblade"),
  weaponDamage: real("weapon_damage").notNull().default(12),
  attackSpeed: real("attack_speed").notNull().default(1),
  rarity: text("rarity", { enum: ["Common", "Uncommon", "Rare", "Epic", "Legendary", "Relic"] }).notNull().default("Common"),
  armorName: text("armor_name").notNull().default("Traveler Cloak"),
  armorDefense: integer("armor_defense").notNull().default(0),
  charmName: text("charm_name").notNull().default("None"),
  trinketName: text("trinket_name").notNull().default("None"),
  critChance: real("crit_chance").notNull().default(0.05),
  keys: integer("keys").notNull().default(0),
  vehicleKeyOwned: integer("vehicle_key_owned", { mode: "boolean" }).notNull().default(false),
  lifesteal: real("lifesteal").notNull().default(0),
  thorns: real("thorns").notNull().default(0),
  dashReduction: real("dash_reduction").notNull().default(0),
  moveSpeed: real("move_speed").notNull().default(0),
  pickupRadius: real("pickup_radius").notNull().default(0),
  items: text("items", { mode: "json" }).$type<string[]>().notNull().default([]),
  storedItems: text("stored_items", { mode: "json" }).$type<string[]>().notNull().default([]),
  gunAmmoState: text("gun_ammo_state", { mode: "json" }).$type<Array<{ name: string; magazine: number; reserve: number }>>().notNull().default([]),
  questState: text("quest_state", { enum: ["not_started", "active", "complete"] }).notNull().default("not_started"),
  questTravelOut: integer("quest_travel_out", { mode: "boolean" }).notNull().default(false),
  questTravelBack: integer("quest_travel_back", { mode: "boolean" }).notNull().default(false),
  rareLootDrops: text("rare_loot_drops", { mode: "json" }).$type<Array<{ id: number; itemId: string; x: number; y: number }>>().notNull().default([]),
  kills: integer("kills").notNull().default(0),
  roomsCleared: integer("rooms_cleared").notNull().default(0),
  bossesDefeated: integer("bosses_defeated").notNull().default(0),
  runsStarted: integer("runs_started").notNull().default(1),
  openedChestIds: text("opened_chest_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  claimedPickupIds: text("claimed_pickup_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  claimedBreakableIds: text("claimed_breakable_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  defeatedEnemyIds: text("defeated_enemy_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  enemyRespawns: text("enemy_respawns", { mode: "json" }).$type<Array<{ id: number; respawnAt: number }>>().notNull().default([]),
  clearedRoomIds: text("cleared_room_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  secretOpenedRoomIds: text("secret_opened_room_ids", { mode: "json" }).$type<number[]>().notNull().default([]),
  exploredCells: text("explored_cells", { mode: "json" }).$type<string[]>().notNull().default([]),
  truckX: real("truck_x").notNull().default(1580),
  truckY: real("truck_y").notNull().default(15745),
  truckFuel: real("truck_fuel").notNull().default(82),
  truckHp: real("truck_hp").notNull().default(180),
  vehicles: text("vehicles", { mode: "json" }).$type<Array<{ id: string; x: number; y: number; hp: number; fuel: number; owned: boolean; inventory: string[] }>>().notNull().default([]),
  dogAdopted: integer("dog_adopted", { mode: "boolean" }).notNull().default(false),
  dogLevel: integer("dog_level").notNull().default(1),
  dogX: real("dog_x").notNull().default(1210),
  dogY: real("dog_y").notNull().default(15715),
  dogHp: real("dog_hp").notNull().default(64),
  dogKills: integer("dog_kills").notNull().default(0),
  chestsOpened: integer("chests_opened").notNull().default(0),
  runStartedAt: text("run_started_at").notNull().default(""),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
}, (table) => [uniqueIndex("game_save_owner_key_unique").on(table.ownerKey)]);
